# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProgramUpdate.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.WindowModal)
        Form.resize(997, 668)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Form.setMouseTracking(False)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(20, 10, 961, 651))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_4.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_4.setSpacing(10)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.gridLayoutWidget_3)
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 30, 211, 71))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setVerticalSpacing(9)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.ser_detect_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ser_detect_button.setObjectName("ser_detect_button")
        self.gridLayout.addWidget(self.ser_detect_button, 1, 0, 1, 1)
        self.ser_open_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        self.ser_open_button.setPalette(palette)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.ser_open_button.setFont(font)
        self.ser_open_button.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.ser_open_button.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.ser_open_button.setAcceptDrops(False)
        self.ser_open_button.setAutoFillBackground(True)
        self.ser_open_button.setCheckable(True)
        self.ser_open_button.setChecked(False)
        self.ser_open_button.setAutoDefault(True)
        self.ser_open_button.setDefault(False)
        self.ser_open_button.setFlat(False)
        self.ser_open_button.setObjectName("ser_open_button")
        self.gridLayout.addWidget(self.ser_open_button, 1, 1, 1, 1)
        self.ser_com_combo = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.ser_com_combo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ser_com_combo.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.ser_com_combo.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.ser_com_combo.setDuplicatesEnabled(False)
        self.ser_com_combo.setFrame(False)
        self.ser_com_combo.setObjectName("ser_com_combo")
        self.gridLayout.addWidget(self.ser_com_combo, 0, 1, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.gridLayoutWidget_3)
        self.groupBox_2.setObjectName("groupBox_2")
        self.Msg_TextEdit = QtWidgets.QTextBrowser(self.groupBox_2)
        self.Msg_TextEdit.setEnabled(True)
        self.Msg_TextEdit.setGeometry(QtCore.QRect(10, 20, 681, 91))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.Msg_TextEdit.sizePolicy().hasHeightForWidth())
        self.Msg_TextEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.Msg_TextEdit.setFont(font)
        self.Msg_TextEdit.setAcceptDrops(True)
        self.Msg_TextEdit.setReadOnly(True)
        self.Msg_TextEdit.setObjectName("Msg_TextEdit")
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 3)
        self.gridLayout_4.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.gridLayoutWidget_3)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_3)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(1, 20, 941, 471))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_3.setContentsMargins(10, 0, 10, 0)
        self.gridLayout_3.setSpacing(10)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.DownloadSlect_comboBox = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.DownloadSlect_comboBox.sizePolicy().hasHeightForWidth())
        self.DownloadSlect_comboBox.setSizePolicy(sizePolicy)
        self.DownloadSlect_comboBox.setInputMethodHints(QtCore.Qt.ImhPreferLatin)
        self.DownloadSlect_comboBox.setFrame(True)
        self.DownloadSlect_comboBox.setObjectName("DownloadSlect_comboBox")
        self.gridLayout_3.addWidget(self.DownloadSlect_comboBox, 0, 1, 1, 1)
        self.download_button = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.download_button.setEnabled(True)
        self.download_button.setObjectName("download_button")
        self.gridLayout_3.addWidget(self.download_button, 0, 8, 1, 1)
        self.Audio_checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.Audio_checkBox.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Audio_checkBox.setFont(font)
        self.Audio_checkBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.Audio_checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Audio_checkBox.setChecked(False)
        self.Audio_checkBox.setAutoRepeat(False)
        self.Audio_checkBox.setTristate(False)
        self.Audio_checkBox.setObjectName("Audio_checkBox")
        self.gridLayout_3.addWidget(self.Audio_checkBox, 2, 0, 1, 1)
        self.DigitalIO_checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.DigitalIO_checkBox.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.DigitalIO_checkBox.setFont(font)
        self.DigitalIO_checkBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.DigitalIO_checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DigitalIO_checkBox.setChecked(False)
        self.DigitalIO_checkBox.setAutoRepeat(False)
        self.DigitalIO_checkBox.setTristate(False)
        self.DigitalIO_checkBox.setObjectName("DigitalIO_checkBox")
        self.gridLayout_3.addWidget(self.DigitalIO_checkBox, 4, 0, 1, 1)
        self.AnalogIO_checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.AnalogIO_checkBox.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.AnalogIO_checkBox.setFont(font)
        self.AnalogIO_checkBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.AnalogIO_checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.AnalogIO_checkBox.setChecked(False)
        self.AnalogIO_checkBox.setAutoRepeat(False)
        self.AnalogIO_checkBox.setTristate(False)
        self.AnalogIO_checkBox.setObjectName("AnalogIO_checkBox")
        self.gridLayout_3.addWidget(self.AnalogIO_checkBox, 3, 0, 1, 1)
        self.PcieBase_checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.PcieBase_checkBox.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.PcieBase_checkBox.setFont(font)
        self.PcieBase_checkBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.PcieBase_checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PcieBase_checkBox.setChecked(False)
        self.PcieBase_checkBox.setAutoRepeat(False)
        self.PcieBase_checkBox.setTristate(False)
        self.PcieBase_checkBox.setObjectName("PcieBase_checkBox")
        self.gridLayout_3.addWidget(self.PcieBase_checkBox, 9, 0, 1, 1)
        self.AnalogVideo_checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.AnalogVideo_checkBox.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.AnalogVideo_checkBox.setFont(font)
        self.AnalogVideo_checkBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.AnalogVideo_checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.AnalogVideo_checkBox.setChecked(False)
        self.AnalogVideo_checkBox.setAutoRepeat(False)
        self.AnalogVideo_checkBox.setTristate(False)
        self.AnalogVideo_checkBox.setObjectName("AnalogVideo_checkBox")
        self.gridLayout_3.addWidget(self.AnalogVideo_checkBox, 6, 0, 1, 1)
        self.PScontrol_checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.PScontrol_checkBox.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.PScontrol_checkBox.setFont(font)
        self.PScontrol_checkBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.PScontrol_checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PScontrol_checkBox.setChecked(False)
        self.PScontrol_checkBox.setAutoRepeat(False)
        self.PScontrol_checkBox.setTristate(False)
        self.PScontrol_checkBox.setObjectName("PScontrol_checkBox")
        self.gridLayout_3.addWidget(self.PScontrol_checkBox, 5, 0, 1, 1)
        self.DigitalVideo_checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.DigitalVideo_checkBox.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.DigitalVideo_checkBox.setFont(font)
        self.DigitalVideo_checkBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.DigitalVideo_checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DigitalVideo_checkBox.setChecked(False)
        self.DigitalVideo_checkBox.setAutoRepeat(False)
        self.DigitalVideo_checkBox.setTristate(False)
        self.DigitalVideo_checkBox.setObjectName("DigitalVideo_checkBox")
        self.gridLayout_3.addWidget(self.DigitalVideo_checkBox, 7, 0, 1, 1)
        self.LVDS_checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.LVDS_checkBox.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.LVDS_checkBox.setFont(font)
        self.LVDS_checkBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.LVDS_checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.LVDS_checkBox.setChecked(False)
        self.LVDS_checkBox.setAutoRepeat(False)
        self.LVDS_checkBox.setTristate(False)
        self.LVDS_checkBox.setObjectName("LVDS_checkBox")
        self.gridLayout_3.addWidget(self.LVDS_checkBox, 8, 0, 1, 1)
        self.BoardRefresh_button = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.BoardRefresh_button.setObjectName("BoardRefresh_button")
        self.gridLayout_3.addWidget(self.BoardRefresh_button, 0, 0, 1, 1)
        self.Progress_bar = QtWidgets.QProgressBar(self.gridLayoutWidget_2)
        self.Progress_bar.setProperty("value", 99)
        self.Progress_bar.setObjectName("Progress_bar")
        self.gridLayout_3.addWidget(self.Progress_bar, 0, 2, 1, 6)
        self.allNodeID_checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.allNodeID_checkBox.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.allNodeID_checkBox.setFont(font)
        self.allNodeID_checkBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.allNodeID_checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.allNodeID_checkBox.setChecked(False)
        self.allNodeID_checkBox.setAutoRepeat(False)
        self.allNodeID_checkBox.setTristate(False)
        self.allNodeID_checkBox.setObjectName("allNodeID_checkBox")
        self.gridLayout_3.addWidget(self.allNodeID_checkBox, 1, 0, 1, 1)
        self.Box1_checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.Box1_checkBox.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Box1_checkBox.setFont(font)
        self.Box1_checkBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.Box1_checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Box1_checkBox.setCheckable(False)
        self.Box1_checkBox.setChecked(False)
        self.Box1_checkBox.setAutoRepeat(False)
        self.Box1_checkBox.setTristate(False)
        self.Box1_checkBox.setObjectName("Box1_checkBox")
        self.gridLayout_3.addWidget(self.Box1_checkBox, 1, 2, 1, 1)
        self.Box5_checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.Box5_checkBox.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Box5_checkBox.setFont(font)
        self.Box5_checkBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.Box5_checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Box5_checkBox.setCheckable(False)
        self.Box5_checkBox.setChecked(False)
        self.Box5_checkBox.setAutoRepeat(False)
        self.Box5_checkBox.setTristate(False)
        self.Box5_checkBox.setObjectName("Box5_checkBox")
        self.gridLayout_3.addWidget(self.Box5_checkBox, 1, 6, 1, 1)
        self.Box4_checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.Box4_checkBox.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Box4_checkBox.setFont(font)
        self.Box4_checkBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.Box4_checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Box4_checkBox.setCheckable(False)
        self.Box4_checkBox.setChecked(False)
        self.Box4_checkBox.setAutoRepeat(False)
        self.Box4_checkBox.setTristate(False)
        self.Box4_checkBox.setObjectName("Box4_checkBox")
        self.gridLayout_3.addWidget(self.Box4_checkBox, 1, 5, 1, 1)
        self.Box3_checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.Box3_checkBox.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Box3_checkBox.setFont(font)
        self.Box3_checkBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.Box3_checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Box3_checkBox.setCheckable(False)
        self.Box3_checkBox.setChecked(False)
        self.Box3_checkBox.setAutoRepeat(False)
        self.Box3_checkBox.setTristate(False)
        self.Box3_checkBox.setObjectName("Box3_checkBox")
        self.gridLayout_3.addWidget(self.Box3_checkBox, 1, 4, 1, 1)
        self.Box0_checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.Box0_checkBox.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.Box0_checkBox.setFont(font)
        self.Box0_checkBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.Box0_checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Box0_checkBox.setCheckable(False)
        self.Box0_checkBox.setChecked(False)
        self.Box0_checkBox.setAutoRepeat(False)
        self.Box0_checkBox.setTristate(False)
        self.Box0_checkBox.setObjectName("Box0_checkBox")
        self.gridLayout_3.addWidget(self.Box0_checkBox, 1, 1, 1, 1)
        self.Box2_checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.Box2_checkBox.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Box2_checkBox.setFont(font)
        self.Box2_checkBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.Box2_checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Box2_checkBox.setCheckable(False)
        self.Box2_checkBox.setChecked(False)
        self.Box2_checkBox.setAutoRepeat(False)
        self.Box2_checkBox.setTristate(False)
        self.Box2_checkBox.setObjectName("Box2_checkBox")
        self.gridLayout_3.addWidget(self.Box2_checkBox, 1, 3, 1, 1)
        self.Box6_checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.Box6_checkBox.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Box6_checkBox.setFont(font)
        self.Box6_checkBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.Box6_checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Box6_checkBox.setCheckable(False)
        self.Box6_checkBox.setChecked(False)
        self.Box6_checkBox.setAutoRepeat(False)
        self.Box6_checkBox.setTristate(False)
        self.Box6_checkBox.setObjectName("Box6_checkBox")
        self.gridLayout_3.addWidget(self.Box6_checkBox, 1, 7, 1, 1)
        self.Box7_checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.Box7_checkBox.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Box7_checkBox.setFont(font)
        self.Box7_checkBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.Box7_checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Box7_checkBox.setCheckable(False)
        self.Box7_checkBox.setChecked(False)
        self.Box7_checkBox.setAutoRepeat(False)
        self.Box7_checkBox.setTristate(False)
        self.Box7_checkBox.setObjectName("Box7_checkBox")
        self.gridLayout_3.addWidget(self.Box7_checkBox, 1, 8, 1, 1)
        self.gridLayout_3.setColumnStretch(0, 1)
        self.gridLayout_3.setColumnStretch(1, 1)
        self.gridLayout_3.setColumnStretch(2, 1)
        self.gridLayout_3.setColumnStretch(3, 1)
        self.gridLayout_3.setColumnStretch(4, 1)
        self.gridLayout_3.setColumnStretch(5, 1)
        self.gridLayout_3.setColumnStretch(6, 1)
        self.gridLayout_3.setColumnStretch(7, 1)
        self.gridLayout_3.setColumnStretch(8, 1)
        self.gridLayout_3.setRowStretch(0, 1)
        self.gridLayout_3.setRowStretch(1, 1)
        self.gridLayout_3.setRowStretch(2, 1)
        self.gridLayout_3.setRowStretch(3, 1)
        self.gridLayout_3.setRowStretch(4, 1)
        self.gridLayout_3.setRowStretch(5, 1)
        self.gridLayout_3.setRowStretch(6, 1)
        self.gridLayout_3.setRowStretch(7, 1)
        self.gridLayout_3.setRowStretch(8, 1)
        self.gridLayout_3.setRowStretch(9, 1)
        self.gridLayout_4.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.gridLayout_4.setRowStretch(0, 1)
        self.gridLayout_4.setRowStretch(1, 4)

        self.retranslateUi(Form)
        self.ser_com_combo.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "ProgramUpdate"))
        self.groupBox.setTitle(_translate("Form", "串口设置"))
        self.label.setText(_translate("Form", "串口："))
        self.ser_detect_button.setText(_translate("Form", "检测串口"))
        self.ser_open_button.setText(_translate("Form", "打开"))
        self.groupBox_2.setTitle(_translate("Form", "提示消息"))
        self.groupBox_3.setTitle(_translate("Form", "板卡节点"))
        self.download_button.setText(_translate("Form", "开始下载"))
        self.Audio_checkBox.setText(_translate("Form", "音频板"))
        self.DigitalIO_checkBox.setText(_translate("Form", "数字IO板"))
        self.AnalogIO_checkBox.setText(_translate("Form", "模拟IO板"))
        self.PcieBase_checkBox.setText(_translate("Form", "底板"))
        self.AnalogVideo_checkBox.setText(_translate("Form", "模拟信号"))
        self.PScontrol_checkBox.setText(_translate("Form", "电源板"))
        self.DigitalVideo_checkBox.setText(_translate("Form", "数字信号"))
        self.LVDS_checkBox.setText(_translate("Form", "LVDS板"))
        self.BoardRefresh_button.setText(_translate("Form", "刷新节点"))
        self.allNodeID_checkBox.setText(_translate("Form", "ALL"))
        self.Box1_checkBox.setText(_translate("Form", "1"))
        self.Box5_checkBox.setText(_translate("Form", "机箱 5"))
        self.Box4_checkBox.setText(_translate("Form", "机箱 4"))
        self.Box3_checkBox.setText(_translate("Form", "机箱 3"))
        self.Box0_checkBox.setText(_translate("Form", "机箱 0"))
        self.Box2_checkBox.setText(_translate("Form", "机箱 2"))
        self.Box6_checkBox.setText(_translate("Form", "机箱 6"))
        self.Box7_checkBox.setText(_translate("Form", "机箱 7"))

