# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProgramUpdate.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.WindowModal)
        Form.resize(1022, 732)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setBaseSize(QtCore.QSize(1, 1))
        Form.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Form.setMouseTracking(False)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_4.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_4.setSpacing(10)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setVerticalSpacing(9)
        self.gridLayout.setObjectName("gridLayout")
        self.ctrl_220V_button = QtWidgets.QPushButton(self.groupBox)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        self.ctrl_220V_button.setPalette(palette)
        self.ctrl_220V_button.setCheckable(True)
        self.ctrl_220V_button.setObjectName("ctrl_220V_button")
        self.gridLayout.addWidget(self.ctrl_220V_button, 2, 1, 1, 1)
        self.ser_open_button = QtWidgets.QPushButton(self.groupBox)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        self.ser_open_button.setPalette(palette)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.ser_open_button.setFont(font)
        self.ser_open_button.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.ser_open_button.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.ser_open_button.setAcceptDrops(False)
        self.ser_open_button.setAutoFillBackground(False)
        self.ser_open_button.setCheckable(True)
        self.ser_open_button.setChecked(False)
        self.ser_open_button.setAutoDefault(False)
        self.ser_open_button.setDefault(False)
        self.ser_open_button.setFlat(False)
        self.ser_open_button.setObjectName("ser_open_button")
        self.gridLayout.addWidget(self.ser_open_button, 0, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 0, 1, 2)
        self.timeEdit = QtWidgets.QTimeEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeEdit.sizePolicy().hasHeightForWidth())
        self.timeEdit.setSizePolicy(sizePolicy)
        self.timeEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.timeEdit.setReadOnly(True)
        self.timeEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.timeEdit.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.timeEdit.setCurrentSection(QtWidgets.QDateTimeEdit.SecondSection)
        self.timeEdit.setCurrentSectionIndex(2)
        self.timeEdit.setTime(QtCore.QTime(0, 0, 1))
        self.timeEdit.setObjectName("timeEdit")
        self.gridLayout.addWidget(self.timeEdit, 2, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.Msg_TextEdit = QtWidgets.QTextBrowser(self.groupBox_2)
        self.Msg_TextEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.Msg_TextEdit.sizePolicy().hasHeightForWidth())
        self.Msg_TextEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.Msg_TextEdit.setFont(font)
        self.Msg_TextEdit.setAcceptDrops(True)
        self.Msg_TextEdit.setReadOnly(True)
        self.Msg_TextEdit.setObjectName("Msg_TextEdit")
        self.gridLayout_6.addWidget(self.Msg_TextEdit, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 3)
        self.gridLayout_4.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_3.setContentsMargins(10, 0, 10, 0)
        self.gridLayout_3.setSpacing(10)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.PcieBase_checkBox_2 = QtWidgets.QCheckBox(self.groupBox_3)
        self.PcieBase_checkBox_2.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.PcieBase_checkBox_2.setFont(font)
        self.PcieBase_checkBox_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.PcieBase_checkBox_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PcieBase_checkBox_2.setChecked(False)
        self.PcieBase_checkBox_2.setAutoRepeat(False)
        self.PcieBase_checkBox_2.setTristate(False)
        self.PcieBase_checkBox_2.setObjectName("PcieBase_checkBox_2")
        self.gridLayout_3.addWidget(self.PcieBase_checkBox_2, 10, 0, 1, 1)
        self.Box0_checkBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.Box0_checkBox.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.Box0_checkBox.setFont(font)
        self.Box0_checkBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.Box0_checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Box0_checkBox.setCheckable(False)
        self.Box0_checkBox.setChecked(False)
        self.Box0_checkBox.setAutoRepeat(False)
        self.Box0_checkBox.setTristate(False)
        self.Box0_checkBox.setObjectName("Box0_checkBox")
        self.gridLayout_3.addWidget(self.Box0_checkBox, 1, 1, 1, 1)
        self.PScontrol_checkBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.PScontrol_checkBox.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.PScontrol_checkBox.setFont(font)
        self.PScontrol_checkBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.PScontrol_checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PScontrol_checkBox.setChecked(False)
        self.PScontrol_checkBox.setAutoRepeat(False)
        self.PScontrol_checkBox.setTristate(False)
        self.PScontrol_checkBox.setObjectName("PScontrol_checkBox")
        self.gridLayout_3.addWidget(self.PScontrol_checkBox, 5, 0, 1, 1)
        self.Audio_checkBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.Audio_checkBox.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Audio_checkBox.setFont(font)
        self.Audio_checkBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.Audio_checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Audio_checkBox.setChecked(False)
        self.Audio_checkBox.setAutoRepeat(False)
        self.Audio_checkBox.setTristate(False)
        self.Audio_checkBox.setObjectName("Audio_checkBox")
        self.gridLayout_3.addWidget(self.Audio_checkBox, 2, 0, 1, 1)
        self.Progress_bar = QtWidgets.QProgressBar(self.groupBox_3)
        self.Progress_bar.setProperty("value", 99)
        self.Progress_bar.setObjectName("Progress_bar")
        self.gridLayout_3.addWidget(self.Progress_bar, 0, 2, 1, 6)
        self.DigitalVideo_checkBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.DigitalVideo_checkBox.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.DigitalVideo_checkBox.setFont(font)
        self.DigitalVideo_checkBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.DigitalVideo_checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DigitalVideo_checkBox.setChecked(False)
        self.DigitalVideo_checkBox.setAutoRepeat(False)
        self.DigitalVideo_checkBox.setTristate(False)
        self.DigitalVideo_checkBox.setObjectName("DigitalVideo_checkBox")
        self.gridLayout_3.addWidget(self.DigitalVideo_checkBox, 7, 0, 1, 1)
        self.PcieBase_checkBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.PcieBase_checkBox.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.PcieBase_checkBox.setFont(font)
        self.PcieBase_checkBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.PcieBase_checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PcieBase_checkBox.setChecked(False)
        self.PcieBase_checkBox.setAutoRepeat(False)
        self.PcieBase_checkBox.setTristate(False)
        self.PcieBase_checkBox.setObjectName("PcieBase_checkBox")
        self.gridLayout_3.addWidget(self.PcieBase_checkBox, 9, 0, 1, 1)
        self.AnalogIO_checkBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.AnalogIO_checkBox.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.AnalogIO_checkBox.setFont(font)
        self.AnalogIO_checkBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.AnalogIO_checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.AnalogIO_checkBox.setChecked(False)
        self.AnalogIO_checkBox.setAutoRepeat(False)
        self.AnalogIO_checkBox.setTristate(False)
        self.AnalogIO_checkBox.setObjectName("AnalogIO_checkBox")
        self.gridLayout_3.addWidget(self.AnalogIO_checkBox, 3, 0, 1, 1)
        self.AnalogVideo_checkBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.AnalogVideo_checkBox.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.AnalogVideo_checkBox.setFont(font)
        self.AnalogVideo_checkBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.AnalogVideo_checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.AnalogVideo_checkBox.setChecked(False)
        self.AnalogVideo_checkBox.setAutoRepeat(False)
        self.AnalogVideo_checkBox.setTristate(False)
        self.AnalogVideo_checkBox.setObjectName("AnalogVideo_checkBox")
        self.gridLayout_3.addWidget(self.AnalogVideo_checkBox, 6, 0, 1, 1)
        self.PcieBase_checkBox_3 = QtWidgets.QCheckBox(self.groupBox_3)
        self.PcieBase_checkBox_3.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.PcieBase_checkBox_3.setFont(font)
        self.PcieBase_checkBox_3.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.PcieBase_checkBox_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PcieBase_checkBox_3.setChecked(False)
        self.PcieBase_checkBox_3.setAutoRepeat(False)
        self.PcieBase_checkBox_3.setTristate(False)
        self.PcieBase_checkBox_3.setObjectName("PcieBase_checkBox_3")
        self.gridLayout_3.addWidget(self.PcieBase_checkBox_3, 11, 0, 1, 1)
        self.Box7_checkBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.Box7_checkBox.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Box7_checkBox.setFont(font)
        self.Box7_checkBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.Box7_checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Box7_checkBox.setCheckable(False)
        self.Box7_checkBox.setChecked(False)
        self.Box7_checkBox.setAutoRepeat(False)
        self.Box7_checkBox.setTristate(False)
        self.Box7_checkBox.setObjectName("Box7_checkBox")
        self.gridLayout_3.addWidget(self.Box7_checkBox, 1, 8, 1, 1)
        self.Box5_checkBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.Box5_checkBox.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Box5_checkBox.setFont(font)
        self.Box5_checkBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.Box5_checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Box5_checkBox.setCheckable(False)
        self.Box5_checkBox.setChecked(False)
        self.Box5_checkBox.setAutoRepeat(False)
        self.Box5_checkBox.setTristate(False)
        self.Box5_checkBox.setObjectName("Box5_checkBox")
        self.gridLayout_3.addWidget(self.Box5_checkBox, 1, 6, 1, 1)
        self.LVDS_checkBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.LVDS_checkBox.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.LVDS_checkBox.setFont(font)
        self.LVDS_checkBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.LVDS_checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.LVDS_checkBox.setChecked(False)
        self.LVDS_checkBox.setAutoRepeat(False)
        self.LVDS_checkBox.setTristate(False)
        self.LVDS_checkBox.setObjectName("LVDS_checkBox")
        self.gridLayout_3.addWidget(self.LVDS_checkBox, 8, 0, 1, 1)
        self.allNodeID_checkBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.allNodeID_checkBox.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.allNodeID_checkBox.setFont(font)
        self.allNodeID_checkBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.allNodeID_checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.allNodeID_checkBox.setChecked(False)
        self.allNodeID_checkBox.setAutoRepeat(False)
        self.allNodeID_checkBox.setTristate(False)
        self.allNodeID_checkBox.setObjectName("allNodeID_checkBox")
        self.gridLayout_3.addWidget(self.allNodeID_checkBox, 1, 0, 1, 1)
        self.Box1_checkBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.Box1_checkBox.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Box1_checkBox.setFont(font)
        self.Box1_checkBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.Box1_checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Box1_checkBox.setCheckable(False)
        self.Box1_checkBox.setChecked(False)
        self.Box1_checkBox.setAutoRepeat(False)
        self.Box1_checkBox.setTristate(False)
        self.Box1_checkBox.setObjectName("Box1_checkBox")
        self.gridLayout_3.addWidget(self.Box1_checkBox, 1, 2, 1, 1)
        self.Box6_checkBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.Box6_checkBox.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Box6_checkBox.setFont(font)
        self.Box6_checkBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.Box6_checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Box6_checkBox.setCheckable(False)
        self.Box6_checkBox.setChecked(False)
        self.Box6_checkBox.setAutoRepeat(False)
        self.Box6_checkBox.setTristate(False)
        self.Box6_checkBox.setObjectName("Box6_checkBox")
        self.gridLayout_3.addWidget(self.Box6_checkBox, 1, 7, 1, 1)
        self.Box3_checkBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.Box3_checkBox.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Box3_checkBox.setFont(font)
        self.Box3_checkBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.Box3_checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Box3_checkBox.setCheckable(False)
        self.Box3_checkBox.setChecked(False)
        self.Box3_checkBox.setAutoRepeat(False)
        self.Box3_checkBox.setTristate(False)
        self.Box3_checkBox.setObjectName("Box3_checkBox")
        self.gridLayout_3.addWidget(self.Box3_checkBox, 1, 4, 1, 1)
        self.BoardRefresh_button = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BoardRefresh_button.sizePolicy().hasHeightForWidth())
        self.BoardRefresh_button.setSizePolicy(sizePolicy)
        self.BoardRefresh_button.setObjectName("BoardRefresh_button")
        self.gridLayout_3.addWidget(self.BoardRefresh_button, 0, 0, 1, 1)
        self.Box4_checkBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.Box4_checkBox.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Box4_checkBox.setFont(font)
        self.Box4_checkBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.Box4_checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Box4_checkBox.setCheckable(False)
        self.Box4_checkBox.setChecked(False)
        self.Box4_checkBox.setAutoRepeat(False)
        self.Box4_checkBox.setTristate(False)
        self.Box4_checkBox.setObjectName("Box4_checkBox")
        self.gridLayout_3.addWidget(self.Box4_checkBox, 1, 5, 1, 1)
        self.PcieBase_checkBox_4 = QtWidgets.QCheckBox(self.groupBox_3)
        self.PcieBase_checkBox_4.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.PcieBase_checkBox_4.setFont(font)
        self.PcieBase_checkBox_4.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.PcieBase_checkBox_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PcieBase_checkBox_4.setChecked(False)
        self.PcieBase_checkBox_4.setAutoRepeat(False)
        self.PcieBase_checkBox_4.setTristate(False)
        self.PcieBase_checkBox_4.setObjectName("PcieBase_checkBox_4")
        self.gridLayout_3.addWidget(self.PcieBase_checkBox_4, 12, 0, 1, 1)
        self.Box2_checkBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.Box2_checkBox.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Box2_checkBox.setFont(font)
        self.Box2_checkBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.Box2_checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Box2_checkBox.setCheckable(False)
        self.Box2_checkBox.setChecked(False)
        self.Box2_checkBox.setAutoRepeat(False)
        self.Box2_checkBox.setTristate(False)
        self.Box2_checkBox.setObjectName("Box2_checkBox")
        self.gridLayout_3.addWidget(self.Box2_checkBox, 1, 3, 1, 1)
        self.download_button = QtWidgets.QPushButton(self.groupBox_3)
        self.download_button.setEnabled(True)
        self.download_button.setObjectName("download_button")
        self.gridLayout_3.addWidget(self.download_button, 0, 8, 1, 1)
        self.DigitalIO_checkBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.DigitalIO_checkBox.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.DigitalIO_checkBox.setFont(font)
        self.DigitalIO_checkBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.DigitalIO_checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DigitalIO_checkBox.setChecked(False)
        self.DigitalIO_checkBox.setAutoRepeat(False)
        self.DigitalIO_checkBox.setTristate(False)
        self.DigitalIO_checkBox.setObjectName("DigitalIO_checkBox")
        self.gridLayout_3.addWidget(self.DigitalIO_checkBox, 4, 0, 1, 1)
        self.Lvds_comboBox = QtWidgets.QComboBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Lvds_comboBox.sizePolicy().hasHeightForWidth())
        self.Lvds_comboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.Lvds_comboBox.setFont(font)
        self.Lvds_comboBox.setObjectName("Lvds_comboBox")
        self.Lvds_comboBox.addItem("")
        self.Lvds_comboBox.addItem("")
        self.Lvds_comboBox.addItem("")
        self.Lvds_comboBox.addItem("")
        self.Lvds_comboBox.addItem("")
        self.Lvds_comboBox.addItem("")
        self.Lvds_comboBox.addItem("")
        self.Lvds_comboBox.addItem("")
        self.Lvds_comboBox.addItem("")
        self.Lvds_comboBox.addItem("")
        self.gridLayout_3.addWidget(self.Lvds_comboBox, 0, 1, 1, 1)
        self.gridLayout_3.setColumnMinimumWidth(0, 2)
        self.gridLayout_3.setColumnMinimumWidth(1, 1)
        self.gridLayout_3.setColumnMinimumWidth(2, 1)
        self.gridLayout_3.setColumnMinimumWidth(3, 1)
        self.gridLayout_3.setColumnMinimumWidth(4, 1)
        self.gridLayout_3.setColumnMinimumWidth(5, 1)
        self.gridLayout_3.setColumnMinimumWidth(6, 1)
        self.gridLayout_3.setColumnMinimumWidth(7, 1)
        self.gridLayout_3.setColumnMinimumWidth(8, 1)
        self.gridLayout_3.setRowMinimumHeight(0, 2)
        self.gridLayout_3.setRowMinimumHeight(1, 1)
        self.gridLayout_3.setRowMinimumHeight(2, 1)
        self.gridLayout_3.setRowMinimumHeight(3, 1)
        self.gridLayout_3.setRowMinimumHeight(4, 1)
        self.gridLayout_3.setRowMinimumHeight(5, 1)
        self.gridLayout_3.setRowMinimumHeight(6, 1)
        self.gridLayout_3.setRowMinimumHeight(7, 1)
        self.gridLayout_3.setRowMinimumHeight(8, 1)
        self.gridLayout_3.setRowMinimumHeight(9, 1)
        self.gridLayout_3.setRowMinimumHeight(10, 1)
        self.gridLayout_3.setRowMinimumHeight(11, 1)
        self.gridLayout_3.setRowMinimumHeight(12, 1)
        self.gridLayout_3.setColumnStretch(0, 2)
        self.gridLayout_3.setColumnStretch(1, 1)
        self.gridLayout_3.setColumnStretch(2, 1)
        self.gridLayout_3.setColumnStretch(3, 1)
        self.gridLayout_3.setColumnStretch(4, 1)
        self.gridLayout_3.setColumnStretch(5, 1)
        self.gridLayout_3.setColumnStretch(6, 1)
        self.gridLayout_3.setColumnStretch(7, 1)
        self.gridLayout_3.setColumnStretch(8, 1)
        self.gridLayout_3.setRowStretch(0, 2)
        self.gridLayout_3.setRowStretch(1, 1)
        self.gridLayout_3.setRowStretch(2, 1)
        self.gridLayout_3.setRowStretch(3, 1)
        self.gridLayout_3.setRowStretch(4, 1)
        self.gridLayout_3.setRowStretch(5, 1)
        self.gridLayout_3.setRowStretch(6, 1)
        self.gridLayout_3.setRowStretch(7, 1)
        self.gridLayout_3.setRowStretch(8, 1)
        self.gridLayout_3.setRowStretch(9, 1)
        self.gridLayout_3.setRowStretch(10, 1)
        self.gridLayout_3.setRowStretch(11, 1)
        self.gridLayout_3.setRowStretch(12, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.gridLayout_4.setRowStretch(0, 1)
        self.gridLayout_4.setRowStretch(1, 4)
        self.gridLayout_2.addLayout(self.gridLayout_4, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "ProgramUpdate"))
        self.groupBox.setTitle(_translate("Form", "串口设置"))
        self.ctrl_220V_button.setText(_translate("Form", "220V"))
        self.ctrl_220V_button.setShortcut(_translate("Form", "F4"))
        self.ser_open_button.setText(_translate("Form", "打开"))
        self.ser_open_button.setShortcut(_translate("Form", "F6"))
        self.lineEdit.setText(_translate("Form", "00 00 00 00 00 00 00 00"))
        self.timeEdit.setDisplayFormat(_translate("Form", "hh:mm:ss"))
        self.groupBox_2.setTitle(_translate("Form", "提示消息"))
        self.groupBox_3.setTitle(_translate("Form", "板卡节点"))
        self.PcieBase_checkBox_2.setText(_translate("Form", "模拟 FPGA"))
        self.Box0_checkBox.setText(_translate("Form", "机箱 0"))
        self.PScontrol_checkBox.setText(_translate("Form", "电源板"))
        self.Audio_checkBox.setText(_translate("Form", "音频板"))
        self.DigitalVideo_checkBox.setText(_translate("Form", "数字信号"))
        self.PcieBase_checkBox.setText(_translate("Form", "底板"))
        self.AnalogIO_checkBox.setText(_translate("Form", "模拟IO板"))
        self.AnalogVideo_checkBox.setText(_translate("Form", "模拟信号"))
        self.PcieBase_checkBox_3.setText(_translate("Form", "数字 FPGA"))
        self.Box7_checkBox.setText(_translate("Form", "机箱 7"))
        self.Box5_checkBox.setText(_translate("Form", "机箱 5"))
        self.LVDS_checkBox.setText(_translate("Form", "LVDS板"))
        self.allNodeID_checkBox.setText(_translate("Form", "ALL"))
        self.Box1_checkBox.setText(_translate("Form", "机箱 1"))
        self.Box6_checkBox.setText(_translate("Form", "机箱 6"))
        self.Box3_checkBox.setText(_translate("Form", "机箱 3"))
        self.BoardRefresh_button.setText(_translate("Form", "刷新节点"))
        self.BoardRefresh_button.setShortcut(_translate("Form", "F5"))
        self.Box4_checkBox.setText(_translate("Form", "机箱 4"))
        self.PcieBase_checkBox_4.setText(_translate("Form", "LVDS FPGA"))
        self.Box2_checkBox.setText(_translate("Form", "机箱 2"))
        self.download_button.setText(_translate("Form", "开始下载"))
        self.DigitalIO_checkBox.setText(_translate("Form", "数字IO板"))
        self.Lvds_comboBox.setItemText(0, _translate("Form", "NORMAL"))
        self.Lvds_comboBox.setItemText(1, _translate("Form", "LVDS"))
        self.Lvds_comboBox.setItemText(2, _translate("Form", "N10"))
        self.Lvds_comboBox.setItemText(3, _translate("Form", "N86_1"))
        self.Lvds_comboBox.setItemText(4, _translate("Form", "N81"))
        self.Lvds_comboBox.setItemText(5, _translate("Form", "PT320"))
        self.Lvds_comboBox.setItemText(6, _translate("Form", "N86_2"))
        self.Lvds_comboBox.setItemText(7, _translate("Form", "PT320_2"))
        self.Lvds_comboBox.setItemText(8, _translate("Form", "EXT_2"))
        self.Lvds_comboBox.setItemText(9, _translate("Form", "Bootloader"))

