# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ProgramVideoIn.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(888, 659)
        MainWindow.setMinimumSize(QtCore.QSize(654, 359))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(1072, 692))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.ip_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.ip_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.ip_lineEdit.setObjectName("ip_lineEdit")
        self.gridLayout_4.addWidget(self.ip_lineEdit, 0, 0, 1, 1)
        self.select_file = QtWidgets.QPushButton(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        self.select_file.setPalette(palette)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.select_file.setFont(font)
        self.select_file.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.select_file.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.select_file.setAcceptDrops(False)
        self.select_file.setToolTip("")
        self.select_file.setToolTipDuration(0)
        self.select_file.setAutoFillBackground(False)
        self.select_file.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.select_file.setCheckable(False)
        self.select_file.setChecked(False)
        self.select_file.setAutoDefault(False)
        self.select_file.setDefault(False)
        self.select_file.setFlat(False)
        self.select_file.setObjectName("select_file")
        self.gridLayout_4.addWidget(self.select_file, 0, 2, 1, 1)
        self.send_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.send_pushButton.setObjectName("send_pushButton")
        self.gridLayout_4.addWidget(self.send_pushButton, 0, 3, 1, 1)
        self.connect_button = QtWidgets.QPushButton(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        self.connect_button.setPalette(palette)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.connect_button.setFont(font)
        self.connect_button.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.connect_button.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.connect_button.setAcceptDrops(False)
        self.connect_button.setToolTipDuration(0)
        self.connect_button.setAutoFillBackground(False)
        self.connect_button.setCheckable(True)
        self.connect_button.setChecked(False)
        self.connect_button.setAutoDefault(False)
        self.connect_button.setDefault(False)
        self.connect_button.setFlat(False)
        self.connect_button.setObjectName("connect_button")
        self.gridLayout_4.addWidget(self.connect_button, 0, 1, 1, 1)
        self.gridLayout_4.setColumnStretch(0, 1)
        self.gridLayout_4.setColumnStretch(1, 1)
        self.gridLayout_4.setColumnStretch(2, 3)
        self.gridLayout_4.setColumnStretch(3, 1)
        self.gridLayout_3.addLayout(self.gridLayout_4, 4, 0, 2, 1)
        self.Send_LineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.Send_LineEdit.setEnabled(False)
        self.Send_LineEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.Send_LineEdit.setObjectName("Send_LineEdit")
        self.gridLayout_3.addWidget(self.Send_LineEdit, 1, 0, 1, 1)
        self.Msg_TextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.Msg_TextEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.Msg_TextEdit.setReadOnly(True)
        self.Msg_TextEdit.setObjectName("Msg_TextEdit")
        self.gridLayout_3.addWidget(self.Msg_TextEdit, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 888, 26))
        self.menubar.setObjectName("menubar")
        self.menumenu = QtWidgets.QMenu(self.menubar)
        self.menumenu.setObjectName("menumenu")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 17, 21))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.statusbar.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.statusbar.setFont(font)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionquit = QtWidgets.QAction(MainWindow)
        self.actionquit.setObjectName("actionquit")
        self.menumenu.addAction(self.actionquit)
        self.menubar.addAction(self.menumenu.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ip_lineEdit.setToolTip(_translate("MainWindow", "输入ip地址"))
        # self.ip_lineEdit.setText(_translate("MainWindow", "192.168.5.2"))
        self.ip_lineEdit.setText(_translate("MainWindow", "192.168.0.16"))
        self.select_file.setText(_translate("MainWindow", "选择文件"))
        self.select_file.setShortcut(_translate("MainWindow", "F6"))
        self.send_pushButton.setText(_translate("MainWindow", "发送"))
        self.connect_button.setToolTip(_translate("MainWindow", "网络连接"))
        self.connect_button.setText(_translate("MainWindow", "连接"))
        self.connect_button.setShortcut(_translate("MainWindow", "F6"))
        self.Msg_TextEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600; color:#ff0000;\">使用说明：</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600; color:#ff0000;\">1.输入正确的ip地址，连接</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600; color:#ff0000;\">2.发送</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt; color:#000000;\"><br /></p></body></html>"))
        self.menumenu.setTitle(_translate("MainWindow", "Menu"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionquit.setText(_translate("MainWindow", "Quit"))

